package com.typex.android;

import android.content.Context;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.List;

final class TypeXAndroidConfig {
    static final String PREFS="typex_keyboard", KEY="TypeX.currentKeyboard";
    String name="TypeX",backgroundHex="#0B0B12",keyDefaultHex="#171724",textHex="#FFFFFF",accentHex="#635BFF",keyPressedHex="#3D36A8";
    double rowSpacing=6,keySpacing=5,keyHeight=42,keyboardHeight=260,opacity=1;
    boolean haptics=true,sounds=false,autoCapitalize=true,doubleSpacePeriod=true,smartQuotes=true,smartDashes=true;
    final List<Row> rows=new ArrayList<>();
    static final class Row{final List<Key> keys=new ArrayList<>();}
    static final class Key{String label="",output="",backgroundHex="#171724",foregroundHex="#FFFFFF",pressedHex="#635BFF",action="text";double width=1,height=1,cornerRadius=9,fontSize=16;int fontWeight=600;boolean haptic=true,sound=false;String longPressAction="",longPressOutput="",swipeUpAction="",swipeUpOutput="",swipeDownAction="",swipeDownOutput="",swipeLeftAction="",swipeLeftOutput="",swipeRightAction="",swipeRightOutput="";}
    static TypeXAndroidConfig load(Context c){String j=c.getSharedPreferences(PREFS,0).getString(KEY,null);if(j!=null)try{return fromJson(j);}catch(Exception ignored){}return defaults();}
    static String loadJson(Context c){return c.getSharedPreferences(PREFS,0).getString(KEY,toJson(defaults()));}
    static void save(Context c,String j)throws Exception{fromJson(j);c.getSharedPreferences(PREFS,0).edit().putString(KEY,j).apply();}
    static TypeXAndroidConfig defaults(){TypeXAndroidConfig c=new TypeXAndroidConfig();add(c,"QWERTYUIOP");add(c,"ASDFGHJKL");add(c,"ZXCVBNM");Row r=new Row();r.keys.add(key("⌫","",1.4,"backspace"));r.keys.add(key("space"," ",4.8,"space"));r.keys.add(key("↵","\n",1.4,"returnKey"));c.rows.add(r);return c;}
    static void add(TypeXAndroidConfig c,String s){Row r=new Row();for(char ch:s.toCharArray()){String x=String.valueOf(ch);r.keys.add(key(x,x.toLowerCase(),1,"text"));}c.rows.add(r);}
    static Key key(String l,String o,double w,String a){Key k=new Key();k.label=l;k.output=o;k.width=w;k.action=a;return k;}
    static TypeXAndroidConfig fromJson(String j)throws Exception{JSONObject r=new JSONObject(j);TypeXAndroidConfig c=new TypeXAndroidConfig();c.name=r.optString("name","TypeX");c.backgroundHex=r.optString("backgroundHex",c.backgroundHex);c.keyDefaultHex=r.optString("keyDefaultHex",c.keyDefaultHex);c.textHex=r.optString("textHex",c.textHex);c.accentHex=r.optString("accentHex",c.accentHex);c.keyPressedHex=r.optString("keyPressedHex",c.keyPressedHex);c.rowSpacing=r.optDouble("rowSpacing",6);c.keySpacing=r.optDouble("keySpacing",5);c.keyHeight=r.optDouble("keyHeight",42);c.keyboardHeight=r.optDouble("keyboardHeight",260);c.opacity=r.optDouble("opacity",1);c.haptics=r.optBoolean("haptics",true);c.sounds=r.optBoolean("sounds",false);c.autoCapitalize=r.optBoolean("autoCapitalize",true);c.doubleSpacePeriod=r.optBoolean("doubleSpacePeriod",true);c.smartQuotes=r.optBoolean("smartQuotes",true);c.smartDashes=r.optBoolean("smartDashes",true);JSONArray rs=r.optJSONArray("rows");if(rs!=null)for(int i=0;i<rs.length();i++){JSONObject ro=rs.optJSONObject(i);if(ro==null)continue;JSONArray ks=ro.optJSONArray("keys");if(ks==null)continue;Row row=new Row();for(int z=0;z<ks.length();z++){JSONObject o=ks.optJSONObject(z);if(o!=null)row.keys.add(parseKey(o,c));}if(!row.keys.isEmpty())c.rows.add(row);}return c.rows.isEmpty()?defaults():c;}
    static Key parseKey(JSONObject o,TypeXAndroidConfig c){Key k=new Key();k.label=o.optString("label","");k.output=o.optString("output","");k.width=o.optDouble("width",1);k.height=o.optDouble("height",1);k.cornerRadius=o.optDouble("cornerRadius",9);k.fontSize=o.optDouble("fontSize",16);k.fontWeight=o.optInt("fontWeight",600);k.backgroundHex=o.optString("backgroundHex",c.keyDefaultHex);k.foregroundHex=o.optString("foregroundHex",c.textHex);k.pressedHex=o.optString("pressedHex",c.keyPressedHex);k.action=o.optString("action","text");k.haptic=o.optBoolean("haptic",c.haptics);k.sound=o.optBoolean("sound",c.sounds);k.longPressAction=o.optString("longPressAction","");k.longPressOutput=o.optString("longPressOutput","");k.swipeUpAction=o.optString("swipeUpAction","");k.swipeUpOutput=o.optString("swipeUpOutput","");k.swipeDownAction=o.optString("swipeDownAction","");k.swipeDownOutput=o.optString("swipeDownOutput","");k.swipeLeftAction=o.optString("swipeLeftAction","");k.swipeLeftOutput=o.optString("swipeLeftOutput","");k.swipeRightAction=o.optString("swipeRightAction","");k.swipeRightOutput=o.optString("swipeRightOutput","");return k;}
    static String toJson(TypeXAndroidConfig c){try{JSONObject r=new JSONObject();r.put("name",c.name);r.put("backgroundHex",c.backgroundHex);r.put("keyDefaultHex",c.keyDefaultHex);r.put("textHex",c.textHex);r.put("accentHex",c.accentHex);r.put("keyPressedHex",c.keyPressedHex);r.put("rowSpacing",c.rowSpacing);r.put("keySpacing",c.keySpacing);r.put("keyHeight",c.keyHeight);r.put("keyboardHeight",c.keyboardHeight);r.put("opacity",c.opacity);r.put("haptics",c.haptics);r.put("sounds",c.sounds);r.put("autoCapitalize",c.autoCapitalize);r.put("doubleSpacePeriod",c.doubleSpacePeriod);r.put("smartQuotes",c.smartQuotes);r.put("smartDashes",c.smartDashes);JSONArray rs=new JSONArray();for(Row row:c.rows){JSONObject ro=new JSONObject();JSONArray ks=new JSONArray();for(Key k:row.keys){JSONObject o=new JSONObject();o.put("label",k.label);o.put("output",k.output);o.put("width",k.width);o.put("height",k.height);o.put("cornerRadius",k.cornerRadius);o.put("fontSize",k.fontSize);o.put("fontWeight",k.fontWeight);o.put("backgroundHex",k.backgroundHex);o.put("foregroundHex",k.foregroundHex);o.put("pressedHex",k.pressedHex);o.put("action",k.action);o.put("haptic",k.haptic);o.put("sound",k.sound);o.put("longPressAction",k.longPressAction);o.put("longPressOutput",k.longPressOutput);o.put("swipeUpAction",k.swipeUpAction);o.put("swipeUpOutput",k.swipeUpOutput);o.put("swipeDownAction",k.swipeDownAction);o.put("swipeDownOutput",k.swipeDownOutput);o.put("swipeLeftAction",k.swipeLeftAction);o.put("swipeLeftOutput",k.swipeLeftOutput);o.put("swipeRightAction",k.swipeRightAction);o.put("swipeRightOutput",k.swipeRightOutput);ks.put(o);}ro.put("keys",ks);rs.put(ro);}r.put("rows",rs);return r.toString();}catch(Exception e){return "{}";}}
    static int color(String h,int fallback){try{return android.graphics.Color.parseColor(h);}catch(Exception e){return fallback;}}
}